# Generated by Django 4.1 on 2022-08-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "author_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True, unique=True)),
                ("screen_name", models.CharField(max_length=255, null=True)),
                ("followers", models.IntegerField(default=0, null=True)),
                ("following", models.IntegerField(default=0, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                ("location", models.CharField(max_length=255, null=True)),
                ("bio", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword_text", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateField(null=True)),
                ("is_hashtag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "tweet_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("message", models.TextField(max_length=280, null=True)),
                ("created_at", models.DateField(null=True)),
                ("retweet_count", models.IntegerField(default=0, null=True)),
                ("favorite_count", models.IntegerField(default=0, null=True)),
                ("reply_count", models.IntegerField(default=0, null=True)),
                (
                    "keyword",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="tweets",
                        to="app_twhunter.keyword",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_twhunter.author",
                    ),
                ),
            ],
        ),
    ]
