# Generated by Django 4.1 on 2022-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_twhunter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="quote_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
