# Generated by Django 4.1 on 2022-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_twhunter", "0002_tweet_quote_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="author",
            name="created_at",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="created_at",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
