# Generated by Django 4.1 on 2022-08-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_twhunter",
            "0003_remove_keyword_created_at_alter_author_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="keyword",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="app_twhunter.keyword"
            ),
        ),
    ]
