# Generated by Django 4.1 on 2022-08-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_twhunter", "0005_alter_tweet_keyword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="user",
        ),
        migrations.AddField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_twhunter.author",
            ),
        ),
    ]
