# Generated by Django 4.1 on 2022-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_twhunter", "0006_remove_tweet_user_tweet_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="keyword",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="app_twhunter.keyword"
            ),
        ),
    ]
