# Generated by Django 4.1 on 2022-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_twhunter", "0010_alter_tweet_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="counter",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="keyword",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="app_twhunter.keyword"
            ),
        ),
    ]
