# Generated by Django 4.1 on 2022-08-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_twhunter", "0011_keyword_counter_alter_tweet_keyword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="counter",
        ),
    ]
