# Generated by Django 4.1 on 2022-08-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_twhunter", "0013_keyword_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="counter",
        ),
    ]
